version: '3'
services:
  web:
    image: ${IMAGE}
    #command: python -u app.py
    #command: tail -F anything
    ports:
      - "5000:5000"
    #volumes:
    # - .:/app
    links:
      - mongo
  
  mongo:
    image: mongo:3.6.1
    volumes:
      - db:/data/db
  

volumes:
  db:
networks:
  default:
    external:
      name: portfolio