version: '3'
services:
  web:
    build: .
    command: python3 -u app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    links:
      - mongo
  mongo:
    image: mongo:3.6.1
    ports:
      - "27017:27017"
    volumes:
      - db:/data/db

volumes:
  db: