version: '3'
services:

  mongo:
    image: mongo:3.6.1
    volumes:
      - db:/data/db
  web:
    build: .
    #command: python -u app.py
    command: tail -F anything
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    links:
      - mongo
  

volumes:
  db: