version: '3'
services:
  web:
    image: golo-portfolio
    environment:
      - MONGODB_URI=mongodb://mongo:27017/
    #build: . 
    #command: python -u app.py
    #command: tail -F anything
    ports:
      - "5000:5000"
    #volumes:
    # - .:/app
    links:
      - mongo
  
  mongo:
    #image: mongo:3.6.1
    image: bitnami/mongodb:6.0.1-debian-11-r0
    volumes:
      - db_mongo:/bitnami/mongodb
  

volumes:
  db_mongo:
networks:
  default:
    external:
      name: portfolio