apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}--app
  labels:
    app: flask-app
spec:
  replicas: {{ .Values.app.scale }}
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image:  644435390668.dkr.ecr.us-east-2.amazonaws.com/golo-portfolio:{{ .Values.app.tag }}
        envFrom:
          - configMapRef:
              name: {{ .Release.Name }}--configmap
        resources:
          requests:
            memory: {{ .Values.app.resources.requests.memory }}
            cpu: {{ .Values.app.resources.requests.cpu }}
          limits:
            memory: {{ .Values.app.resources.limits.memory }}
            cpu: {{ .Values.app.resources.limits.cpu }}
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}--service
spec:
  type: {{ .Values.app.type }}
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000